### ISSUE TITLE
this theme still work?

### ISSUE THREAD

**Issue by jacquescrocker** [cherring/vibrant-ink#4]
if so, can you update installation instructions. I followed the current one and it doesnt seem to show up anywhere in atom.

**Comment by cherring** [comment]
Hi @jacquescrocker I'm sorry, I didn't see this. I am still using it, so I think it should work. I need to update a deprecation in the newest atom, I will look at updating install info at the same time.

**Comment by cherring** [comment]
@jacquescrocker I have updated the theme. You can install it from the Install Themes and packages from the settings screen in Atom.
